*** Starting uWSGI 2.0.14 (64bit) on [Thu Dec 15 22:25:32 2016] ***
compiled with version: 5.4.0 20160609 on 14 December 2016 21:23:21
os: Linux-4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016
nodename: ubuntu
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/ayocrosss/mysite
writing pidfile to /home/ayocrosss/mysite/mysite-master.pid # create a pidfile
detected binary path: /home/ayocrosss/py3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/ayocrosss/mysite
your processes number limit is 7779
limiting address space of processes...
your process address space limit is 134217728 bytes (128 MB)
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/ayocrosss/mysite/mysite.sock fd 3
Python version: 3.5.2 (default, Nov 17 2016, 17:05:23)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xba9cc0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 800360 bytes (781 KB) for 10 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./mysite/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/ayocrosss/py3/lib/python3.5/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/ayocrosss/py3/lib/python3.5/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/ayocrosss/py3/lib/python3.5/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/home/ayocrosss/py3/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ayocrosss/py3/lib/python3.5/site-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/ayocrosss/py3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named 'blog'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 4689)
spawned uWSGI worker 1 (pid: 4691, cores: 1)
spawned uWSGI worker 2 (pid: 4692, cores: 1)
spawned uWSGI worker 3 (pid: 4693, cores: 1)
spawned uWSGI worker 4 (pid: 4694, cores: 1)
spawned uWSGI worker 5 (pid: 4695, cores: 1)
spawned uWSGI worker 6 (pid: 4696, cores: 1)
spawned uWSGI worker 7 (pid: 4697, cores: 1)
spawned uWSGI worker 8 (pid: 4698, cores: 1)
spawned uWSGI worker 9 (pid: 4699, cores: 1)
spawned uWSGI worker 10 (pid: 4700, cores: 1)
*** Starting uWSGI 2.0.14 (64bit) on [Thu Dec 15 22:25:42 2016] ***
compiled with version: 5.4.0 20160609 on 14 December 2016 21:23:21
os: Linux-4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016
nodename: ubuntu
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/ayocrosss/mysite
writing pidfile to /home/ayocrosss/mysite/mysite-master.pid # create a pidfile
detected binary path: /home/ayocrosss/py3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/ayocrosss/mysite
your processes number limit is 7779
limiting address space of processes...
your process address space limit is 134217728 bytes (128 MB)
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/ayocrosss/mysite/mysite.sock fd 3
Python version: 3.5.2 (default, Nov 17 2016, 17:05:23)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xc77cc0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 800360 bytes (781 KB) for 10 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./mysite/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/ayocrosss/py3/lib/python3.5/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/ayocrosss/py3/lib/python3.5/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/ayocrosss/py3/lib/python3.5/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/home/ayocrosss/py3/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ayocrosss/py3/lib/python3.5/site-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/ayocrosss/py3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named 'blog'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 4705)
spawned uWSGI worker 1 (pid: 4707, cores: 1)
spawned uWSGI worker 2 (pid: 4708, cores: 1)
spawned uWSGI worker 3 (pid: 4709, cores: 1)
spawned uWSGI worker 4 (pid: 4710, cores: 1)
spawned uWSGI worker 5 (pid: 4711, cores: 1)
spawned uWSGI worker 6 (pid: 4712, cores: 1)
spawned uWSGI worker 7 (pid: 4713, cores: 1)
spawned uWSGI worker 8 (pid: 4714, cores: 1)
spawned uWSGI worker 9 (pid: 4715, cores: 1)
spawned uWSGI worker 10 (pid: 4716, cores: 1)
*** Starting uWSGI 2.0.14 (64bit) on [Thu Dec 15 22:26:23 2016] ***
compiled with version: 5.4.0 20160609 on 14 December 2016 21:23:21
os: Linux-4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016
nodename: ubuntu
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/ayocrosss/mysite
detected binary path: /home/ayocrosss/py3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/ayocrosss/mysite
your processes number limit is 7779
limiting address space of processes...
your process address space limit is 134217728 bytes (128 MB)
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/ayocrosss/mysite/mysite.sock fd 3
Python version: 3.5.2 (default, Nov 17 2016, 17:05:23)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1b54c60
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 800360 bytes (781 KB) for 10 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1b54c60 pid: 4722 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 4722)
spawned uWSGI worker 1 (pid: 4724, cores: 1)
spawned uWSGI worker 2 (pid: 4725, cores: 1)
spawned uWSGI worker 3 (pid: 4726, cores: 1)
spawned uWSGI worker 4 (pid: 4727, cores: 1)
spawned uWSGI worker 5 (pid: 4728, cores: 1)
spawned uWSGI worker 6 (pid: 4729, cores: 1)
spawned uWSGI worker 7 (pid: 4730, cores: 1)
spawned uWSGI worker 8 (pid: 4731, cores: 1)
spawned uWSGI worker 9 (pid: 4732, cores: 1)
spawned uWSGI worker 10 (pid: 4733, cores: 1)
*** Starting uWSGI 2.0.14 (64bit) on [Thu Dec 15 22:26:41 2016] ***
compiled with version: 5.4.0 20160609 on 14 December 2016 21:23:21
os: Linux-4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016
nodename: ubuntu
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/ayocrosss/mysite
writing pidfile to /home/ayocrosss/mysite/mysite-master.pid # create a pidfile
detected binary path: /home/ayocrosss/py3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/ayocrosss/mysite
your processes number limit is 7779
limiting address space of processes...
your process address space limit is 134217728 bytes (128 MB)
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/ayocrosss/mysite/mysite.sock fd 3
Python version: 3.5.2 (default, Nov 17 2016, 17:05:23)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x9b0c60
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 800360 bytes (781 KB) for 10 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./mysite/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/ayocrosss/py3/lib/python3.5/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/ayocrosss/py3/lib/python3.5/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/ayocrosss/py3/lib/python3.5/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/home/ayocrosss/py3/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ayocrosss/py3/lib/python3.5/site-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/ayocrosss/py3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named 'blog'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 4739)
spawned uWSGI worker 1 (pid: 4741, cores: 1)
spawned uWSGI worker 2 (pid: 4742, cores: 1)
spawned uWSGI worker 3 (pid: 4743, cores: 1)
spawned uWSGI worker 4 (pid: 4744, cores: 1)
spawned uWSGI worker 5 (pid: 4745, cores: 1)
spawned uWSGI worker 6 (pid: 4746, cores: 1)
spawned uWSGI worker 7 (pid: 4747, cores: 1)
spawned uWSGI worker 8 (pid: 4748, cores: 1)
spawned uWSGI worker 9 (pid: 4749, cores: 1)
spawned uWSGI worker 10 (pid: 4750, cores: 1)
